# Generated by Django 2.1.7 on 2019-02-24 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsUser',
            fields=[
                ('uid', models.OneToOneField(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('sexy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_user',
                'managed': True,
            },
        ),
    ]
