# Generated by Django 2.1.7 on 2019-02-24 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_ch', models.CharField(blank=True, max_length=255, null=True)),
                ('category_py', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'news_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('uniquekey', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('url_num', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_pic_s01', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_pic_s02', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_pic_s03', models.CharField(blank=True, max_length=255, null=True)),
                ('first_p', models.TextField(blank=True, null=True)),
                ('json_comment', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='my_newsApp.NewsCategory')),
            ],
            options={
                'db_table': 'news_info',
                'managed': True,
            },
        ),
    ]
